package com.trade.ace.mapper;

import com.trade.ace.entity.TradeUserMoneyLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TradeUserMoneyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbg.generated
     */
    int insert(TradeUserMoneyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user_money_log
     *
     * @mbg.generated
     */
    List<TradeUserMoneyLog> selectAll();
}