package com.trade.ace.mapper;

import com.trade.ace.entity.TradeGoods;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TradeGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int insert(TradeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    TradeGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    List<TradeGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeGoods record);
}