package com.trade.ace.mapper;

import com.trade.ace.entity.TradeCoupon;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TradeCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int insert(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    TradeCoupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    List<TradeCoupon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TradeCoupon record);
}