package com.trade.ace.mapper;

import com.trade.ace.entity.TradeGoodsNumberLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TradeGoodsNumberLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    int insert(TradeGoodsNumberLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_goods_number_log
     *
     * @mbg.generated
     */
    List<TradeGoodsNumberLog> selectAll();
}